Repository erigones/esdc-ce, pull requests merged in 2019-02, with the labels that each got.

#385 allow upgrading a platform from local custom platform file
  bin/eslib/esdc-platform-upgrade-disk.sh
Labels: SmartOS, enhancement

#404 fix esdc-overlay ADMINOVERLAY_NODE_MAC_MAP
  bin/esdc-overlay
Labels: SmartOS, bug

#411 fix recognition of full disk device file during USB platform upgrade
  bin/eslib/esdc-platform-upgrade-usb.sh
Labels: SmartOS, USB image, bug

#403 Added manual cleanup script
  core/management/commands/cleanup.py
  doc/changelog.rst
Labels: enhancement, support

#410 node upgrade script to 4.0-beta1
  ans/upgrade/node/v4.0-beta1/files/020-ipsec-restore.sh
  ans/upgrade/node/v4.0-beta1/main.sh
Labels: SmartOS

#406 fix node version sort during upgrades
  ans/upgrade/lib/runupgrade.yml
  bin/esdc-node-update
  bin/eslib/functions.sh
Labels: bug

#386 fix source VM deletion after migration
  bin/eslib/functions.sh
  bin/esmigrate
  doc/changelog.rst
Labels: SmartOS, bug

#412 Fixed CPU monitoring script
  ans/upgrade/node/v4.0-beta1/files/monitoring/vm-cpu-monitor
  ans/upgrade/node/v4.0-beta1/main.sh
Labels: USB image, bug

#413 fix migration of delegated dataset with children
  bin/eslib/functions.sh
  bin/esmigrate
  doc/changelog.rst
Labels: SmartOS, bug

#415 Increased number of possible vNICs to 16
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net10.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net11.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net12.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net13.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net14.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net15.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net8.json
  ans/upgrade/mon/v4.0-beta1/files/zabbix_templates/t_vm_network_net9.json
  ans/upgrade/mon/v4.0-beta1/main.yml
  api/vm/define/views.py
  api/vm/define/vm_define_nic.py
  doc/changelog.rst
Labels: API, enhancement

#417 Fixed pip uninstall by setting TMPDIR to the same FS as erigones/envs
  bin/ctl.sh
  doc/changelog.rst
Labels: Service VMs, SmartOS, bug
