Repository erigones/esdc-ce, pull requests merged in 2020-11, with the labels that each got.

#520 Create usb-platform-upgrade.sh
  bin/eslib/usb-platform-upgrade.sh
Labels: SmartOS, USB image, enhancement

#522 Add Italian Language files to danubecloud
  core/settings.py
  gui/locale/it/LC_MESSAGES/django.mo
  gui/locale/it/LC_MESSAGES/django.po
  gui/locale/it/LC_MESSAGES/djangojs.mo
  gui/locale/it/LC_MESSAGES/djangojs.po
  gui/static/gui/img/flags.png
Labels: GUI, enhancement

#517 Add classless delegated reverse DNS zones
  api/dns/domain/utils.py
  api/network/base/serializers.py
  api/system/init.py
  api/vm/define/serializers.py
  gui/templatetags/gui_utils.py
  gui/vm/utils.py
  gui/vm/views.py
  pdns/models/record.py
  vms/models/vm.py
Labels: bug, enhancement

#523 fix pkgin repos in GZ on 2018Q4 and older
  ans/upgrade/node/v4.4/main.sh
  core/version.py
Labels: SmartOS, bug

#525 V4.4 changelog
  doc/changelog.rst
Labels: documentation
